### ISSUE TITLE
リファクタ

### ISSUE THREAD

**Issue by mitsuyoshi-yamazaki** [mitsuyoshi-yamazaki/ALifeGameJam2019#26]
今後さらに複雑な生物/世界を実装するにあたって、生物と世界のレイヤーを分離してインターフェースを定義する

- 生物と世界のレイヤーを分離
  - 世界は常に一定のルール（物理法則）にもとづいて稼働する、生物は世界への働きかけのみを行う
  - ”エネルギー” などは生物がもつのか世界が管理するのがよいのか、難しい概念
- ついでにコンパイラに仕事をさせるためTS化する
  - https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

「ここからここまでが内部状態をもつ生命である」という部分を定義しているのがこのインターフェースにおける抽象化

```swift
// TS忘れたのでSwift

protocol World<T: Rule> {
  // 世界全ての状態
  // Objects がどれだけあるかもここに含まれる
  var state: T.State { get }

  // 世界開闢からの時刻
  var t: Int { get }

  // rule が型でなくインスタンスであるのは、各種パラメータを変更できるようにするため
  // 例：重力加速度を0.5m/s^2とする
  var rule: T { get } 

  // t+1 の世界の状態に進める：state が更新される
  func next()

  // state の状態を描画
  func draw()
}

protocol Rule {
  // このルールにおける状態
  associatedType State

  // 重量、サイズ等 物理演算に必要な属性
  associatedType Property

  // t+1 の状態を算出
  func next(state: State) -> State
}

protocol Object<T: Rule> {
  // 重量、サイズ等 物理演算に必要な属性
  var property: T.Property { get } 
}

class Life: Object {
}
```

---

- 生物と世界を分離できれば、任意の組み合わせをパラメータで与えてホスティングに表示できるかもしれない
- 生物のセンシングは、センサーのスペックを世界に渡して、それに対するセンシング結果を返してもらう形式にすればそれっぽくなるのではないか

**Comment by ayu-mushi** [comment]
責任範囲の分離というのは、「同じ物理法則でも違う生物が居る場合に対応する」「一方を変更した時の他方の変更を最小化する(カプセル化など)」といった目的で行われると考えていいですか

**Comment by mitsuyoshi-yamazaki** [comment]
そうです

実際の生き物は大部分が物理法則にロックインするはずなのであくまで理想の話ですが

**Comment by mitsuyoshi-yamazaki** [comment]
memo

- https://github.com/processing/p5.js
  - Processing と同じところに向かうプロジェクトらしい
  - ProcessingJS と同じことを別個にやっているものか
  - Casey ReasもcontributeしているしTSの型定義ファイルもあるので移行を試してみる
- https://code.visualstudio.com/docs/typescript/typescript-tutorial

**Comment by mitsuyoshi-yamazaki** [comment]
memo

これで生物と物理法則を分離できるが、生物の演算処理は世界のルールに乗っていない

**Comment by mitsuyoshi-yamazaki** [comment]
> 生物と世界のレイヤーを分離

この辺を真面目にやっていくと行き着く「ゲーム世界を簡単に構築できる」というアイデアはゲームエンジンになるので、人工生命世界をどう実装するのがうまいかある程度見えたらUnityあたりで書き直して"人工生命ゲームエンジン"を作りたい

Unityはエディタ自身を書き換えてゲームシステムに合わせたゲームエンジンを作ることができるのが強み
一方であくまでゲームなので、ゲーム時間は実時間と一致する想定であるし、イベントドリブンなところがある

**Comment by ayu-mushi** [comment]
ところでエディタ自身を書き換えるというのはどういう機能ですか
> Unityはエディタ自身を書き換えてゲームシステムに合わせたゲームエンジンを作ることができるのが強み

**Comment by mitsuyoshi-yamazaki** [comment]
UnityをつかってUnityに新規のエディタを追加することができるんです
例えば、標準で入っていない経路探索アルゴリズムを使いたいときに、それを使えるようにする新規のエディタを書いてUnityに組み込む、とか

そしてそのようなエディタもAssetのひとつなので、Asset Storeで公開することができる
利用する人は必要な機能をもつエディタを組み込んでいって、ゲームを作るのに十分な機能をもつ統合開発環境を作る

ゲームに必要となる機能は様々なので、そうやってエディタの方をカスタマイズできるようにしてあります

**Comment by ayu-mushi** [comment]
そんな機能があったのですね。

**Comment by mitsuyoshi-yamazaki** [comment]
done
