### ISSUE TITLE
画像を餌にマッピングして与える

### ISSUE THREAD

**Issue by mitsuyoshi-yamazaki** [mitsuyoshi-yamazaki/ALifeGameJam2019#38]
画像を餌にマッピングして与えたらどうか？
解像度をとても高くしたら油絵フィルターになるのでは

**Comment by ayu-mushi** [comment]
私が思ってたのは画像の画素から生物を生成するのでした

**Comment by mitsuyoshi-yamazaki** [comment]
> 画素から生物を生成する

実装してみて気づいたけれど、エサの色とそのエサを食べる生物の色は異なるのでそうしないと絵にならないですね
